#!/bin/bash
git restore --staged airflow/.env
git restore --staged airflow/.gitignore
git restore --staged airflow/Dockerfile
git restore --staged airflow/dags/dbt_test_dag.py
git restore --staged airflow/dags/load_songs_dag.py
git restore --staged airflow/dags/schema.py
git restore --staged airflow/dags/sql/auth_events.sql
git restore --staged airflow/dags/sql/listen_events.sql
git restore --staged airflow/dags/sql/page_view_events.sql
git restore --staged airflow/dags/streamline_dag.py
git restore --staged airflow/dags/task_templates.py
git restore --staged airflow/docker-compose.yaml
git restore --staged airflow/requirements.txt
git restore --staged dbt/.gitignore
git restore --staged dbt/README.md
git restore --staged dbt/analyses/.gitkeep
git restore --staged dbt/dbt_project.yml
git restore --staged dbt/macros/.gitkeep
git restore --staged dbt/models/core/dim_artists.sql
git restore --staged dbt/models/core/dim_datetime.sql
git restore --staged dbt/models/core/dim_location.sql
git restore --staged dbt/models/core/dim_songs.sql
git restore --staged dbt/models/core/dim_users.sql
git restore --staged dbt/models/core/fact_streams.sql
git restore --staged dbt/models/core/schema.yml
git restore --staged dbt/models/core/wide_streams.sql
git restore --staged dbt/packages.yml
git restore --staged dbt/profiles.yml
git restore --staged dbt/seeds/.gitkeep
git restore --staged dbt/seeds/songs.csv
git restore --staged dbt/seeds/state_codes.csv
git restore --staged dbt/snapshots/.gitkeep
git restore --staged dbt/tests/.gitkeep
git restore --staged eventsim/Dockerfile
git restore --staged eventsim/README.md
git restore --staged eventsim/data/Gaz_zcta_national.txt
git restore --staged eventsim/data/Top1000Surnames.csv
git restore --staged eventsim/data/US.txt
git restore --staged eventsim/data/listen_counts.txt.gz
git restore --staged eventsim/data/songs_analysis.txt.gz
git restore --staged eventsim/data/yob1990.txt
git restore --staged eventsim/eventsim.sh
git restore --staged eventsim/examples/alt-example-config.json
git restore --staged eventsim/examples/example-config.json
git restore --staged eventsim/target/eventsim-assembly-2.0.jar
git restore --staged kafka/docker-compose.yml
git restore --staged kafka/test_connection/data/rides.csv
git restore --staged kafka/test_connection/data/zones.csv
git restore --staged kafka/test_connection/produce_taxi_json.py
git restore --staged scripts/airflow_startup.sh
git restore --staged scripts/eventsim_startup.sh
git restore --staged scripts/exec_commands.sh
git restore --staged scripts/spark_setup.sh
git restore --staged scripts/vm_setup.sh
git restore --staged spark_streaming/schema.py
git restore --staged spark_streaming/stream_all_events.py
git restore --staged spark_streaming/streaming_functions.py
git restore --staged spark_streaming/test_connection/stream_taxi_json.py